version: 2
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - netbsd
      - openbsd
    goarch:
      - amd64
      - arm
      - arm64
      - ppc64le
      - mips64le
      - s390x
    goarm:
      - "5"
      - "7"
    gomips:
      - hardfloat
    main: ./cmd/yubico-piv-checker
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
nfpms:
  -
    package_name: ovh-yubico-piv-checker
    vendor: OVH SAS
    maintainer: Thomas SOËTE <thomas.soete@ovhcloud.com>
    description: Tool to check Yubico PIV Attestation. See https://developers.yubico.com/yubico-piv-tool/Attestation.html
    license: Apache 2.0
    formats:
      - deb
      - rpm
    file_name_template: >-
      {{- trimsuffix .ConventionalFileName .ConventionalExtension -}}
      {{- if and (eq .Arm "6") (eq .ConventionalExtension ".deb") }}6{{ end -}}
      {{- if not (eq .Amd64 "v1")}}{{ .Amd64 }}{{ end -}}
      {{- .ConventionalExtension -}}